baseURL: https://cocochran.xyz
title: charlola.mode
paginate: 5
theme: charlolamode



menu:
    main:
        - name: Contact
          url: contact/
          weight: 30
        - name: Articles
          url: articles/
          weight: 20
        - name: Projects
          url: projects
          weight: 15

     # - name: Categories
        #   url: categories/
        #   weight: 10
        # - name: new Tab
        #   url: mewtab/
        #   weight: defines order of tabs
   


params:
    author: Connor Cochran


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: false
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        enabled: true
        title: Connor Cochran
        description: |

          Hi, my name is Connor.

           I am a student interested in web development, software development, and artificial intelligence. 
        

          I am currently working on a platformer game for a school project.
        imageUrl: "/images/java.jpeg"
        imageTitle: "my image"
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: NEVER GIVE UP!
              url: "https://www.youtube.com/watch?v=tYzMYcUty6s"
    mainSections:
      - articles

    socialIcons:
        - name: patreon
          url: "https://www.patreon.com/user?u=86417490&fan_landing=true&view_as=public"
        - name: github
          url: "https://github.com/CoCochran"
        - name: linkedin
          url: "https://www.linkedin.com/in/connor-cochran-a69241251?trk=public_profile_samename-profile"

      # add more social icons. find more in svg.html file
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

